version: '3.9'
services:
  nest:
    build:
      context: ./
      target: dev
    volumes:
      - .:/app
    command: npm run start:dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    depends_on: 
      - 'database'
    restart: always
  database:
    image: 'mongo'
    container_name: 'mongo'
    environment:
      - MONGO_INITDB_DATABASE=aDatabase
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
    volumes:
      - ./initMongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
      - ./mongo-volume:/data/db
    ports:
      - '27017-27019:27017-27019'
        # command: -vvvv
        # vuejs:
        # build:
        # context: ../front/ 
        # volumes:
        #- '.:/app'
      #- '/app/node_module'
      # ports:
      # - '8081:8080'
